#!/bin/bash

echo "=== Windows Firewall Fix Instructions ==="
echo ""
echo "The server is working correctly. The issue is Windows Firewall"
echo "on the client computer (172.20.10.4) blocking the connection."
echo ""
echo "SOLUTION: Disable Windows Firewall temporarily on the client:"
echo ""
echo "1. Press Win + R, type 'wf.msc', press Enter"
echo "2. Click 'Firewall & network protection'"
echo "3. Click your network type (Private/Public)"
echo "4. Turn OFF 'Microsoft Defender Firewall'"
echo "5. Try accessing: http://172.20.10.10:3000"
echo ""
echo "After confirming it works, either:"
echo "- Turn firewall back on and add port 3000 exception"
echo "- Or keep it disabled for development"
echo ""
echo "=== Alternative: Add Firewall Exception ==="
echo "1. In Windows Firewall settings"
echo "2. Advanced settings → Inbound Rules → New Rule"
echo "3. Port → TCP → 3000 → Allow connection"
echo "4. Apply to all network types"
echo ""
echo "=== Test Commands (run on client) ==="
echo "ping 172.20.10.10"
echo "telnet 172.20.10.10 3000  (if telnet installed)"
echo "curl http://172.20.10.10:3000  (if curl installed)"